// SPDX-FileCopyrightText: 2025 The Kepler Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.36.0. DO NOT EDIT.

package device

import mock "github.com/stretchr/testify/mock"

// MockGPUPowerMeter is an autogenerated mock type for the GPUPowerMeter type
type MockGPUPowerMeter struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *MockGPUPowerMeter) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProcessPower provides a mock function with given fields: pid, gpuID
func (_m *MockGPUPowerMeter) ProcessPower(pid int, gpuID uint) (Power, Energy, error) {
	ret := _m.Called(pid, gpuID)

	var r0 Power
	var r1 Energy
	var r2 error
	if rf, ok := ret.Get(0).(func(int, uint) (Power, Energy, error)); ok {
		return rf(pid, gpuID)
	}
	if rf, ok := ret.Get(0).(func(int, uint) Power); ok {
		r0 = rf(pid, gpuID)
	} else {
		r0 = ret.Get(0).(Power)
	}

	if rf, ok := ret.Get(1).(func(int, uint) Energy); ok {
		r1 = rf(pid, gpuID)
	} else {
		r1 = ret.Get(1).(Energy)
	}

	if rf, ok := ret.Get(2).(func(int, uint) error); ok {
		r2 = rf(pid, gpuID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProcessUtilization provides a mock function with given fields: pid, gpuID
func (_m *MockGPUPowerMeter) ProcessUtilization(pid int, gpuID uint) (*GPUProcessUtilization, error) {
	ret := _m.Called(pid, gpuID)

	var r0 *GPUProcessUtilization
	var r1 error
	if rf, ok := ret.Get(0).(func(int, uint) (*GPUProcessUtilization, error)); ok {
		return rf(pid, gpuID)
	}
	if rf, ok := ret.Get(0).(func(int, uint) *GPUProcessUtilization); ok {
		r0 = rf(pid, gpuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GPUProcessUtilization)
		}
	}

	if rf, ok := ret.Get(1).(func(int, uint) error); ok {
		r1 = rf(pid, gpuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields:
func (_m *MockGPUPowerMeter) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockGPUPowerMeter) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DevicePower provides a mock function with given fields: gpuID
func (_m *MockGPUPowerMeter) DevicePower(gpuID uint) (Power, bool) {
	ret := _m.Called(gpuID)

	var r0 Power
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint) (Power, bool)); ok {
		return rf(gpuID)
	}
	if rf, ok := ret.Get(0).(func(uint) Power); ok {
		r0 = rf(gpuID)
	} else {
		r0 = ret.Get(0).(Power)
	}

	if rf, ok := ret.Get(1).(func(uint) bool); ok {
		r1 = rf(gpuID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Zones provides a mock function with given fields:
func (_m *MockGPUPowerMeter) Zones() ([]GPUEnergyZone, error) {
	ret := _m.Called()

	var r0 []GPUEnergyZone
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]GPUEnergyZone, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []GPUEnergyZone); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]GPUEnergyZone)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGPUPowerMeter creates a new instance of MockGPUPowerMeter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGPUPowerMeter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGPUPowerMeter {
	mock := &MockGPUPowerMeter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
