name: Release

on: #yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-reboot

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      IMG_BASE: quay.io/rh_ee_vprashar

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # NOTE: setting fetch-depth to 0 to retrieve the entire history
          # instead of a shallow -clone so that all tags are fetched as well.
          # This is necessary for computing the VERSION using `git describe`
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true
          check-latest: true

      - name: Login to Image Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMG_BASE }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # - name: make deps
      #   shell: bash
      #   run: make deps
      #
      # - name: Build Image
      #   shell: bash
      #   run: |
      #     make image
      #
      # - name: Push Image
      #   shell: bash
      #   run: |
      #     make push

      - name: Extract version
        shell: bash
        id: version
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=$(echo "$TAG_NAME" | sed 's/-reboot//')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Get the tag name from the push event
          tag_name: ${{ github.ref_name }}
          # Use the tag name as the release name
          name: release-${{ steps.version.outputs.version }}
          # It will look for the .github/release.yml configuration file
          generate_release_notes: true
          draft: false
          # Set prerelease to true if the tag indicates a pre-release (e.g., v1.0.0-beta.1)
          # You might need more complex logic here to determine this based on the tag name
          # prerelease: contains(github.ref_name, '-') # Simple example: tag contains a hyphen
