name: Release

on: #yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-reboot

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io/rh_ee_vprashar
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: make deps
        shell: bash
        run: make deps

      - name: Build Image
        shell: bash
        run: |
          make image
        env:
          IMG_BASE: quay.io/rh_ee_vprashar

      - name: Push Image
        shell: bash
        if: "!startsWith(inputs.registry, 'localhost')"
        run: |
          make push
        env:
          IMG_BASE: quay.io/rh_ee_vprashar

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: COMMIT
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                { "title": "## Features", "labels": ["feat"] },
                { "title": "## Fixes", "labels": ["fix"] }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|compose){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ],
              "pr_template": "#{{NUMBER}} {{TITLE}}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print changelog (for debugging)
        run: |
          echo "Changelog generated:"
          echo "${{ steps.changelog.outputs.changelog }}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2 # Update action version if needed
        with:
          name: ${{ 'release-' + replace(replace(github.ref_name, 'v', ''), '-reboot', '') }}
          body: ${{ steps.changelog.outputs.changelog_output }} # Use the output from the previous step
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
