name: Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for release (e.g., 1.0.0)
        required: true

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          # registry: quay.io/sustainable_computing_io
          registry: quay.io/rh_ee_vprashar
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          # username: ${{ secrets.BOT_NAME }}
          # password: ${{ secrets.BOT_TOKEN }}

      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create release branch
        run: |
          git checkout -b release-${{ github.event.inputs.tag }}

      - name: Tag release branch
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"

      - name: Push release branch with tag
        run: |
          git push origin release-${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Build image
        run: make image
        env:
          IMG_BASE: quay.io/rh_ee_vprashar

      - name: Push image
        run: make push
        env:
          IMG_BASE: quay.io/rh_ee_vprashar

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR to main branch
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Release ${{ github.event.inputs.tag }}
          title: Release ${{ github.event.inputs.tag }}
          body: |
            This PR adds release ${{ github.event.inputs.tag }}.
          branch: release-${{ github.event.inputs.tag }}
          base: reboot
          draft: false
          # assignees:
          # reviewers:
